; ============================================================================
;  Convolver installer script.
;
;  This file is a template: it is deliberately app-agnostic. Every value that
;  differs between applications arrives as a /D preprocessor define from
;  tools/dist/build-installer.ps1, which reads packaging/app.json plus the
;  version resource of the executable that was built.
;
;  Nothing app-specific belongs in this file. Hardcoding a name or a version
;  here would create a second place for it to live, and the whole point of the
;  packager reading the .exe is that there is exactly one.
;
;  Build the installer with:
;      .\tools\dist\build-installer.ps1
;
;  Running ISCC.exe against this file directly fails the guards below, by design.
; ============================================================================

#ifndef AppId
  #error AppId is not defined. Use tools/dist/build-installer.ps1, or pass /DAppId={...}
#endif
#ifndef AppName
  #error AppName is not defined.
#endif
#ifndef AppVersion
  #error AppVersion is not defined.
#endif
#ifndef AppPublisher
  #error AppPublisher is not defined.
#endif
#ifndef ExeName
  #error ExeName is not defined.
#endif
#ifndef RuntimeLogName
  #error RuntimeLogName is not defined.
#endif
#ifndef SourceDir
  #error SourceDir is not defined.
#endif
#ifndef IconFile
  #error IconFile is not defined.
#endif
#ifndef OutputDir
  #error OutputDir is not defined.
#endif
#ifndef OutputBaseFilename
  #error OutputBaseFilename is not defined.
#endif

[Setup]
; AppId is the identity of the application, not of the build. It must never
; change between versions, or upgrades install alongside the previous release
; instead of replacing it, and must be unique per application.
;
; The triple brace is not a typo: Inno treats a lone '{' as the start of a
; directory constant, so a literal one has to be doubled. '{{' collapses to '{',
; then {#AppId} is replaced by the bare GUID from packaging/app.json, and the
; final '}' is literal - giving AppId = {99C8668F-...}.
AppId={{{#AppId}}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}

; Fill in the installer's own version resource. Complete metadata is one of the
; things that keeps heuristic antivirus verdicts away from unsigned binaries.
VersionInfoVersion={#AppVersion}
VersionInfoCompany={#AppPublisher}
VersionInfoProductName={#AppName}
VersionInfoDescription={#AppName} {#AppVersion} Setup

; PrivilegesRequired=lowest selects Inno's non-administrative install mode, so
; Setup never requests elevation and the user never sees the UAC prompt with
; "Publisher: Unknown". {autopf} then resolves to {userpf}, i.e.
; %LOCALAPPDATA%\Programs\<AppName> for a per-user install, instead of requiring
; write access to Program Files.
;
; The overrides setting allows /ALLUSERS or /CURRENTUSER on the command line for
; the occasional machine-wide deployment, without offering a dialog on every run.
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline

; Prerequisite for the application .exe, not for this installer.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
DisableDirPage=auto

UninstallDisplayName={#AppName} {#AppVersion}
UninstallDisplayIcon={app}\{#ExeName}

OutputDir={#OutputDir}
OutputBaseFilename={#OutputBaseFilename}

; SetupIconFile accepts only a real .ico, not the PNG or SVG the build uses
; elsewhere. packaging/icon/appicon.ico is generated by
; tools/icons/make-app-icon.ps1 from the same geometry, at 16/32/48/64/128/256 -
; a wider set than juceaide emits for the executable, and including the 64x64
; that Inno recommends.
SetupIconFile={#IconFile}

Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; ignoreversion: the file is replaced on every install and has no version
; negotiation to do. Only the Release executable ships; never a Debug build, a
; PDB, or a runtime log.
Source: "{#SourceDir}\{#ExeName}"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\{#ExeName}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#ExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#ExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; The application writes its runtime log next to its own executable whenever
; that directory is writable, which it is for a per-user install (and
; %APPDATA% otherwise, which is user data and is deliberately left alone).
Type: files; Name: "{app}\{#RuntimeLogName}"
